name: workflow

on:
  pull_request_target:
    branches: [main]
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: test run
    if: "${{ (github.event_name == 'pull_request_target') !== github.event.pull_request.head.repo.fork  }}"
    steps:
      - name: run
        run: echo "${{ !!github.event.pull_request && github.event.pull_request.head.sha || github.sha }}"
