name: workflow

on:
  pull_request_target:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: test run
    steps:
      - name: run
        run: echo "${{ secrets.SECRET }}"
