name: workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: test run
    steps:
      - name: run
        run: echo "${{ !!github.event.pull_request && github.event.pull_request.head.sha || github.sha }}"
